(* This file is automatically generated.  Do not edit it directly. *)

(** Enum modules *)

module Enum2 = Enum2
module Enum3 = Enum3
module Enum4 = Enum4
module Enum5 = Enum5
module Enum6 = Enum6
module Enum7 = Enum7
module Enum8 = Enum8
module Enum9 = Enum9
module Enum10 = Enum10
module Enum11 = Enum11
module Enum12 = Enum12
module Enum13 = Enum13
module Enum14 = Enum14
module Enum15 = Enum15
module Enum16 = Enum16

(** Tuple modules *)

module Tuple2 = Tuple2
module Tuple3 = Tuple3
module Tuple4 = Tuple4
module Tuple5 = Tuple5
module Tuple6 = Tuple6
module Tuple7 = Tuple7
module Tuple8 = Tuple8
module Tuple9 = Tuple9
module Tuple10 = Tuple10
module Tuple11 = Tuple11
module Tuple12 = Tuple12
module Tuple13 = Tuple13
module Tuple14 = Tuple14
module Tuple15 = Tuple15
module Tuple16 = Tuple16

(** Variant modules *)

module Variant2 = Variant2
module Variant3 = Variant3
module Variant4 = Variant4
module Variant5 = Variant5
module Variant6 = Variant6
module Variant7 = Variant7
module Variant8 = Variant8
module Variant9 = Variant9
module Variant10 = Variant10
module Variant11 = Variant11
module Variant12 = Variant12
module Variant13 = Variant13
module Variant14 = Variant14
module Variant15 = Variant15
module Variant16 = Variant16

(** List modules *)

module List2 = List2
module List3 = List3
module List4 = List4
module List5 = List5
module List6 = List6
module List7 = List7
module List8 = List8
module List9 = List9
module List10 = List10
module List11 = List11
module List12 = List12
module List13 = List13
module List14 = List14
module List15 = List15
module List16 = List16
